FROM python:3.9
WORKDIR /app

COPY PythonServer/requirements.txt PythonServer/wsgi.py PythonServer/ .env ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD [ "gunicorn", "-b", ":5000", "wsgi:app" ]