# builds React front end for nginx
# /api request to wsgi:5000

FROM node:16-alpine as build-step
WORKDIR /demo
ENV PATH /demo/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
COPY ./src ./src
COPY ./public ./public

# npm build instead?
RUN yarn install
RUN yarn build

# Nginx container 
FROM nginx:stable-alpine
COPY --from=build-step /demo/build /user/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
